services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/app
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres_data:
